FROM docker.io/dataeng-dibimbing/flask
USER root

WORKDIR /app

COPY docker/start.sh /start.sh
ENTRYPOINT ["/bin/bash", "/start.sh"]
COPY ./.env /app/.env
COPY ./flask_requirements.txt /app
COPY ./consumer.py /app
RUN pip install -r /app/flask_requirements.txt